/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-03-26 16:57:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cs336project.pkg.*;
import java.io.*;
import java.util.*;
import java.sql.*;

public final class sell_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--Import some libraries that have classes that we need -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Sell</title>\n");
      out.write("</head>\n");
      out.write("\t\t\t");


				if(session.getAttribute("username") == null){
					response.sendRedirect("login.jsp");
				}
			sellUpdate.update();

			
      out.write("\n");
      out.write("<style>\n");
      out.write(".nav {\n");
      out.write("\toverflow: hidden;\n");
      out.write("\topacity: 0.8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav a {\n");
      out.write("\tfloat: left;\n");
      out.write("\tdisplay: block;\n");
      out.write("\tpadding: 10px;\n");
      out.write("\tbackground-color: black;\n");
      out.write("\tfont-family: verdana;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\ttransition-duration: 0.4s;\n");
      out.write("\tcolor: white;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tpadding: 14px 14px;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav a:hover:not(.active) {\n");
      out.write("\tbackground-color: moccasin;\n");
      out.write("\tcolor: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav a.active {\n");
      out.write("\tbackground-color: lightsalmon;\n");
      out.write("\tcolor: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav input {\n");
      out.write("\tfloat: center;\n");
      out.write("\tpadding: 6px;\n");
      out.write("\tmargin-top: 8px;\n");
      out.write("\tmargin-right: 4px;\n");
      out.write("\tmargin-left: 16px;\n");
      out.write("\tborder-style: solid;\n");
      out.write("\tfont-size: 17px;\n");
      out.write("\twidth: 500px;\n");
      out.write("\tbackground-color: transparent;\n");
      out.write("\tcolor: ivory;\n");
      out.write("\tborder-color: ivory;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav input:focus {\n");
      out.write("\toutline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav button {\n");
      out.write("\tpadding: 6px 10px;\n");
      out.write("\tmargin-top: 8px;\n");
      out.write("\tmargin-right: 16px;\n");
      out.write("\tbackground: #ddd;\n");
      out.write("\tfont-size: 17px;\n");
      out.write("\tborder: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tbackground-color: ivory;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav button:hover {\n");
      out.write("\tbackground: #ccc;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("\tfont-family: arial, sans-serif;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("\tcolor: white;\n");
      out.write("\twidth: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("td, th, tr {\n");
      out.write("\tborder: none;\n");
      out.write("\ttext-align: left;\n");
      out.write("\tpadding: 8px;\n");
      out.write("\tbackground-color: black;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("}\n");
      out.write("input[type=submit] {\n");
      out.write("\twidth: 75%;\n");
      out.write("\tpadding: 6px 6px;\n");
      out.write("\tmargin: 2px 0;\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("\tborder: none;\n");
      out.write("\tbackground-color: indianred;\n");
      out.write("\tcolor: white;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\ttransition-duration: 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=submit]:hover {\n");
      out.write("\tbackground-color: firebrick;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("input[type=text]{\n");
      out.write("\n");
      out.write("   \tfont-size: 14px;\n");
      out.write("   \tbackground-color: transparent;\n");
      out.write("   \tcolor:white;\n");
      out.write("   \tfont-family: inherit;\n");
      out.write("\n");
      out.write("}\n");
      out.write("input[type=number]{\n");
      out.write("\n");
      out.write("   \tfont-size: 14px;\n");
      out.write("   \tbackground-color: transparent;\n");
      out.write("   \tcolor:white;\n");
      out.write("   \tfont-family: inherit;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tbackground-image:\n");
      out.write("\t\turl('http://localhost:8080/Project_Group_91/Images/buy.jpg');\n");
      out.write("\tbackground-repeat: no-repeat;\n");
      out.write("\tbackground-attachment: fixed;\n");
      out.write("\tbackground-size: cover;\n");
      out.write("\tfont-family: Verdana, Geneva, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item-info {\n");
      out.write("\tmargin: 8px;\n");
      out.write("\tpadding: 20px;\n");
      out.write("\tcolor: white;\n");
      out.write("\tbackground-color: black;\n");
      out.write("\topacity: 0.8;\n");
      out.write("\tborder-style: solid;\n");
      out.write("\tborder-color: ivory;\n");
      out.write("\tfont-family: Helvetica, Arial, sans-serif;\n");
      out.write("\tfont-size: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".submit-button {\n");
      out.write("\tpadding: 8px;\n");
      out.write("\tbackground: none;\n");
      out.write("\tcolor: white;\n");
      out.write("\tborder: none;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\ttransition-duration: 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".submit-button:hover {\n");
      out.write("\tbackground-color: limegreen;\n");
      out.write("\tcolor: black;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write(".dropdown{\n");
      out.write("\n");
      out.write("\tbackground-color: transparent;\n");
      out.write("\tcolor: white;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\twidth: 200px;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".dropdown:focus{\n");
      out.write("\n");
      out.write("\toutline: none;\n");
      out.write("}\n");
      out.write("input:focus { \n");
      out.write("    outline: none;\n");
      out.write("   \n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"nav\">\n");
      out.write("\t\t<a href=\"userHomepage.jsp\">HOME</a> <a href=\"buy.jsp\">BUY</a> <a\n");
      out.write("\t\t\tclass=\"active\" href=\"sell.jsp\">SELL</a><a href = \"my_products.jsp\">MY PRODUCTS</a>\n");
      out.write("\t\t\t <a href=\"userInbox.jsp\">INBOX</a>\n");
      out.write("\t\t\n");
      out.write("\t\t<a href=\"Logout.jsp\" style=\"float: right;\">LOGOUT</a>\n");
      out.write("\t\t<a href = \"help.jsp\" style=\"float:right;\">HELP</a>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\t<div class=\"item-info\">\n");
      out.write("\t<form method=\"post\" action = \"addItem.jsp\">\n");
      out.write("\t\t<table>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td><label for=\"category\">Pick a Category: &emsp;&emsp;</label></td>\n");
      out.write("\t\t\t<td> <select class=\"dropdown\" name=\"category_name\" id=\"category\" required>\n");
      out.write("\t\t\t\t <option value=\"Select\">Select</option>\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t ");

				 
				 		try{
				 			
				 			ApplicationDB db = new ApplicationDB();
				 			Connection con = db.getConnection();
				 			
				 			String str = "SELECT DISTINCT category_name FROM category";
				 			Statement stmt = con.createStatement();
				 			ResultSet rs = stmt.executeQuery(str);
				 			
				 			while(rs.next()){
				 				
				 			String catg_name = rs.getString("category_name");
				 				
      out.write("\n");
      out.write("\t\t\t\t \t\t\t\t<option value=\"");
      out.print(catg_name);
      out.write('"');
      out.write('>');
      out.print(catg_name);
      out.write("</option>\n");
      out.write("\t\t\t\t \t\t\t\t");

				 			}
				 			
				 			db.closeConnection(con);
				 			
				 		}
				 		catch(Exception e){
				 			out.print(e);
				 		}
				 
				 
      out.write("\n");
      out.write(" \t\t\t\t </select>\n");
      out.write(" \t\t\t</td>\n");
      out.write(" \t\t\t<td>\n");
      out.write(" \t\t\t<a href = \"add_category.jsp\"><button style=\"font-size: 14px; background: transparent; color: white; border: none; cursor: pointer;\" type=\"button\">Add Category</button></a>\n");
      out.write(" \t\t\t</td>\n");
      out.write(" \t\t\t<tr>\n");
      out.write(" \t\t\t<td>Item Name:</td> \n");
      out.write(" \t\t\t<td><input type=\"text\" name = \"item_name\" required></td>\n");
      out.write(" \t\t\t</tr>\n");
      out.write(" \t\t\t<tr>\n");
      out.write(" \t\t\t<td>Minimum Price:</td> \n");
      out.write(" \t\t\t<td><input type=\"number\" name = \"minimum_price\" min=\"1\" required>&emsp;$</td> \n");
      out.write(" \t\t\t</tr>\n");
      out.write(" \t\t\t<tr>\n");
      out.write(" \t\t\t<td>Closing Date:</td> \n");
      out.write(" \t\t\t<td><input type=\"text\" name = \"closing_date\" placeholder=\"YYYY-MM-DD\" required></td>\n");
      out.write(" \t\t\t</tr>\n");
      out.write(" \t\t\t<tr>\n");
      out.write(" \t\t\t<td>Closing Time:</td> \n");
      out.write(" \t\t\t<td><input type=\"text\" name = \"closing_time\" placeholder=\"hh:mm:ss\" required></td>\n");
      out.write(" \t\t\t</tr>\n");
      out.write(" \t\t\t<tr>\n");
      out.write(" \t\t\t<td>Reserve:</td>\n");
      out.write(" \t\t\t<td>\n");
      out.write(" \t\t\t\t<input type=\"radio\" id=\"yes\" value=\"true\" name=\"reserve\">\n");
      out.write(" \t\t\t\t<label for=\"yes\">Yes&emsp;&emsp;</label>\n");
      out.write(" \t\t\t\t<input type=\"radio\" id=\"no\" value=\"false\" name=\"reserve\">\n");
      out.write(" \t\t\t\t<label for=\"no\">No&emsp;&emsp;</label>\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"reserve_value\" id=\"reserve_value\" disabled=\"true\" placeholder=\"Enter Reserve Price\" min = \"1\" required> $\n");
      out.write("\t\t\t\t<script>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tdocument.getElementById('no').onchange = function() {\n");
      out.write("\t\t\t\t\t\n");
      out.write("    \t\t\t\tdocument.getElementById('reserve_value').disabled = this.checked;\n");
      out.write("    \t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tdocument.getElementById('yes').onchange = function() {\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdocument.getElementById('reserve_value').disabled = !(this.checked);\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t</script>\n");
      out.write(" \t\t\t</td>\n");
      out.write(" \t\t\t</tr>\n");
      out.write("\t\t</table><br><br><br>\n");
      out.write("\t\t<div align=\"center\">\n");
      out.write("\t\t<button type=\"submit\" class=\"submit-button\">Submit</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\n");
      out.write("\t</form>\t\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
